import './assets/main.css'
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { firebaseApp } from './firebase'
import App from './App.vue'
import router from './router'

import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import { VDateInput } from 'vuetify/labs/VDateInput'
import { VCalendar } from 'vuetify/labs/VCalendar'
import { VTimePicker } from 'vuetify/lib/labs/components.mjs'
import { VTreeview } from 'vuetify/labs/VTreeview'

const vuetify = createVuetify({
  components: {
    ...components,
    VDateInput,
    VCalendar,
    VTimePicker,
    VTreeview
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        dark: false,
        colors: {
          primary: '#65558F',
          surfaceTint: '#65558F',
          onPrimary: '#FFFFFF',
          primaryContainer: '#E9DDFF',
          onPrimaryContainer: '#211047',
          secondary: '#625B70',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#E8DEF8',
          onSecondaryContainer: '#1E192B',
          tertiary: '#7E5260',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#FFD9E3',
          onTertiaryContainer: '#31101D',
          error: '#BA1A1A',
          onError: '#FFFFFF',
          errorContainer: '#FFDAD6',
          onErrorContainer: '#410002',
          background: '#FDF7FF',
          onBackground: '#1D1B20',
          surface: '#FDF7FF',
          onSurface: '#1D1B20',
          surfaceVariant: '#E7E0EB',
          onSurfaceVariant: '#49454E',
          outline: '#7A757F',
          outlineVariant: '#CAC4CF',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#322F35',
          inverseOnSurface: '#F5EFF7',
          inversePrimary: '#CFBDFE',
          primaryFixed: '#E9DDFF',
          onPrimaryFixed: '#211047',
          primaryFixedDim: '#CFBDFE',
          onPrimaryFixedVariant: '#4D3D75',
          secondaryFixed: '#E8DEF8',
          onSecondaryFixed: '#1E192B',
          secondaryFixedDim: '#CCC2DB',
          onSecondaryFixedVariant: '#4A4458',
          tertiaryFixed: '#FFD9E3',
          onTertiaryFixed: '#31101D',
          tertiaryFixedDim: '#EFB8C8',
          onTertiaryFixedVariant: '#633B48',
          surfaceDim: '#DED8E0',
          surfaceBright: '#FDF7FF',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#F8F2FA',
          surfaceContainer: '#F2ECF4',
          surfaceContainerHigh: '#ECE6EE',
          surfaceContainerHighest: '#E6E0E9'
        }
      },
      lightMediumContrast: {
        dark: false,
        colors: {
          primary: '#493971',
          surfaceTint: '#65558F',
          onPrimary: '#FFFFFF',
          primaryContainer: '#7C6BA7',
          onPrimaryContainer: '#FFFFFF',
          secondary: '#464054',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#787187',
          onSecondaryContainer: '#FFFFFF',
          tertiary: '#5F3744',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#966776',
          onTertiaryContainer: '#FFFFFF',
          error: '#8C0009',
          onError: '#FFFFFF',
          errorContainer: '#DA342E',
          onErrorContainer: '#FFFFFF',
          background: '#FDF7FF',
          onBackground: '#1D1B20',
          surface: '#FDF7FF',
          onSurface: '#1D1B20',
          surfaceVariant: '#E7E0EB',
          onSurfaceVariant: '#45414A',
          outline: '#615D67',
          outlineVariant: '#7D7983',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#322F35',
          inverseOnSurface: '#F5EFF7',
          inversePrimary: '#CFBDFE',
          primaryFixed: '#7C6BA7',
          onPrimaryFixed: '#FFFFFF',
          primaryFixedDim: '#63538C',
          onPrimaryFixedVariant: '#FFFFFF',
          secondaryFixed: '#787187',
          onSecondaryFixed: '#FFFFFF',
          secondaryFixedDim: '#5F596E',
          onSecondaryFixedVariant: '#FFFFFF',
          tertiaryFixed: '#966776',
          onTertiaryFixed: '#FFFFFF',
          tertiaryFixedDim: '#7B4F5D',
          onTertiaryFixedVariant: '#FFFFFF',
          surfaceDim: '#DED8E0',
          surfaceBright: '#FDF7FF',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#F8F2FA',
          surfaceContainer: '#F2ECF4',
          surfaceContainerHigh: '#ECE6EE',
          surfaceContainerHighest: '#E6E0E9'
        }
      },
      lightHighContrast: {
        dark: false,
        colors: {
          primary: '#27174E',
          surfaceTint: '#65558F',
          onPrimary: '#FFFFFF',
          primaryContainer: '#493971',
          onPrimaryContainer: '#FFFFFF',
          secondary: '#251F32',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#464054',
          onSecondaryContainer: '#FFFFFF',
          tertiary: '#391724',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#5F3744',
          onTertiaryContainer: '#FFFFFF',
          error: '#4E0002',
          onError: '#FFFFFF',
          errorContainer: '#8C0009',
          onErrorContainer: '#FFFFFF',
          background: '#FDF7FF',
          onBackground: '#1D1B20',
          surface: '#FDF7FF',
          onSurface: '#000000',
          surfaceVariant: '#E7E0EB',
          onSurfaceVariant: '#25232B',
          outline: '#45414A',
          outlineVariant: '#45414A',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#322F35',
          inverseOnSurface: '#FFFFFF',
          inversePrimary: '#F1E8FF',
          primaryFixed: '#493971',
          onPrimaryFixed: '#FFFFFF',
          primaryFixedDim: '#322359',
          onPrimaryFixedVariant: '#FFFFFF',
          secondaryFixed: '#464054',
          onSecondaryFixed: '#FFFFFF',
          secondaryFixedDim: '#2F2A3D',
          onSecondaryFixedVariant: '#FFFFFF',
          tertiaryFixed: '#5F3744',
          onTertiaryFixed: '#FFFFFF',
          tertiaryFixedDim: '#45212E',
          onTertiaryFixedVariant: '#FFFFFF',
          surfaceDim: '#DED8E0',
          surfaceBright: '#FDF7FF',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#F8F2FA',
          surfaceContainer: '#F2ECF4',
          surfaceContainerHigh: '#ECE6EE',
          surfaceContainerHighest: '#E6E0E9'
        }
      },
      dark: {
        dark: true,
        colors: {
          primary: '#CFBDFE',
          surfaceTint: '#CFBDFE',
          onPrimary: '#36265D',
          primaryContainer: '#4D3D75',
          onPrimaryContainer: '#E9DDFF',
          secondary: '#CCC2DB',
          onSecondary: '#332D41',
          secondaryContainer: '#4A4458',
          onSecondaryContainer: '#E8DEF8',
          tertiary: '#EFB8C8',
          onTertiary: '#4A2532',
          tertiaryContainer: '#633B48',
          onTertiaryContainer: '#FFD9E3',
          error: '#FFB4AB',
          onError: '#690005',
          errorContainer: '#93000A',
          onErrorContainer: '#FFDAD6',
          background: '#141218',
          onBackground: '#E6E0E9',
          surface: '#141218',
          onSurface: '#E6E0E9',
          surfaceVariant: '#49454E',
          onSurfaceVariant: '#CAC4CF',
          outline: '#948F99',
          outlineVariant: '#49454E',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#E6E0E9',
          inverseOnSurface: '#322F35',
          inversePrimary: '#65558F',
          primaryFixed: '#E9DDFF',
          onPrimaryFixed: '#211047',
          primaryFixedDim: '#CFBDFE',
          onPrimaryFixedVariant: '#4D3D75',
          secondaryFixed: '#E8DEF8',
          onSecondaryFixed: '#1E192B',
          secondaryFixedDim: '#CCC2DB',
          onSecondaryFixedVariant: '#4A4458',
          tertiaryFixed: '#FFD9E3',
          onTertiaryFixed: '#31101D',
          tertiaryFixedDim: '#EFB8C8',
          onTertiaryFixedVariant: '#633B48',
          surfaceDim: '#141218',
          surfaceBright: '#3B383E',
          surfaceContainerLowest: '#0F0D13',
          surfaceContainerLow: '#1D1B20',
          surfaceContainer: '#211F24',
          surfaceContainerHigh: '#2B292F',
          surfaceContainerHighest: '#36343A'
        }
      },
      darkMediumContrast: {
        dark: true,
        colors: {
          primary: '#D3C1FF',
          surfaceTint: '#CFBDFE',
          onPrimary: '#1B0942',
          primaryContainer: '#9887C5',
          onPrimaryContainer: '#000000',
          secondary: '#D0C7E0',
          onSecondary: '#181325',
          secondaryContainer: '#958DA4',
          onSecondaryContainer: '#000000',
          tertiary: '#F4BCCC',
          onTertiary: '#2B0B18',
          tertiaryContainer: '#B58392',
          onTertiaryContainer: '#000000',
          error: '#FFBAB1',
          onError: '#370001',
          errorContainer: '#FF5449',
          onErrorContainer: '#000000',
          background: '#141218',
          onBackground: '#E6E0E9',
          surface: '#141218',
          onSurface: '#FFF9FF',
          surfaceVariant: '#49454E',
          onSurfaceVariant: '#CFC8D4',
          outline: '#A6A1AB',
          outlineVariant: '#86818B',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#E6E0E9',
          inverseOnSurface: '#2B292F',
          inversePrimary: '#4E3F76',
          primaryFixed: '#E9DDFF',
          onPrimaryFixed: '#16033D',
          primaryFixedDim: '#CFBDFE',
          onPrimaryFixedVariant: '#3C2C63',
          secondaryFixed: '#E8DEF8',
          onSecondaryFixed: '#130E20',
          secondaryFixedDim: '#CCC2DB',
          onSecondaryFixedVariant: '#393347',
          tertiaryFixed: '#FFD9E3',
          onTertiaryFixed: '#240612',
          tertiaryFixedDim: '#EFB8C8',
          onTertiaryFixedVariant: '#502B38',
          surfaceDim: '#141218',
          surfaceBright: '#3B383E',
          surfaceContainerLowest: '#0F0D13',
          surfaceContainerLow: '#1D1B20',
          surfaceContainer: '#211F24',
          surfaceContainerHigh: '#2B292F',
          surfaceContainerHighest: '#36343A'
        }
      },
      darkHighContrast: {
        dark: true,
        colors: {
          primary: '#FFF9FF',
          surfaceTint: '#CFBDFE',
          onPrimary: '#000000',
          primaryContainer: '#D3C1FF',
          onPrimaryContainer: '#000000',
          secondary: '#FFF9FF',
          onSecondary: '#000000',
          secondaryContainer: '#D0C7E0',
          onSecondaryContainer: '#000000',
          tertiary: '#FFF9F9',
          onTertiary: '#000000',
          tertiaryContainer: '#F4BCCC',
          onTertiaryContainer: '#000000',
          error: '#FFF9F9',
          onError: '#000000',
          errorContainer: '#FFBAB1',
          onErrorContainer: '#000000',
          background: '#141218',
          onBackground: '#E6E0E9',
          surface: '#141218',
          onSurface: '#FFFFFF',
          surfaceVariant: '#49454E',
          onSurfaceVariant: '#FFF9FF',
          outline: '#CFC8D4',
          outlineVariant: '#CFC8D4',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#E6E0E9',
          inverseOnSurface: '#000000',
          inversePrimary: '#2F2056',
          primaryFixed: '#EDE2FF',
          onPrimaryFixed: '#000000',
          primaryFixedDim: '#D3C1FF',
          onPrimaryFixedVariant: '#1B0942',
          secondaryFixed: '#ECE3FC',
          onSecondaryFixed: '#000000',
          secondaryFixedDim: '#D0C7E0',
          onSecondaryFixedVariant: '#181325',
          tertiaryFixed: '#FFDFE7',
          onTertiaryFixed: '#000000',
          tertiaryFixedDim: '#F4BCCC',
          onTertiaryFixedVariant: '#2B0B18',
          surfaceDim: '#141218',
          surfaceBright: '#3B383E',
          surfaceContainerLowest: '#0F0D13',
          surfaceContainerLow: '#1D1B20',
          surfaceContainer: '#211F24',
          surfaceContainerHigh: '#2B292F',
          surfaceContainerHighest: '#36343A'
        }
      }
    }
  }
})

const app = createApp(App)

app.use(createPinia())
app.use(router)
app.use(vuetify)
app.use(firebaseApp)

app.mount('#app')
